version: '3.8'

services:
  backend:
    image: python:3.9-slim
    container_name: sadie-backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "pip install fastapi uvicorn python-multipart python-jose[cryptography] passlib[bcrypt] 
      && cd sadie/web 
      && python -m uvicorn mock_api:app --host 0.0.0.0 --port 8000"

  frontend:
    image: node:18
    container_name: sadie-frontend
    working_dir: /app/sadie/web/static
    volumes:
      - ./:/app
      - frontend_node_modules:/app/sadie/web/static/node_modules
      - frontend_reports:/app/sadie/web/static/reports
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--max_old_space_size=8192
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - BROWSER=none
      - CI=false
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G
    command: >
      bash -c "mkdir -p scripts reports &&
      npm cache clean --force &&
      npm config set legacy-peer-deps true &&
      npm install --no-fund --no-audit &&
      npm install @babel/plugin-proposal-private-property-in-object recharts @material-ui/core@4.12.4 @material-ui/icons @mui/material @mui/icons-material @emotion/react @emotion/styled --no-fund --no-audit &&
      echo 'REACT_APP_API_URL=http://localhost:8000' > .env &&
      echo 'REACT_APP_WS_URL=ws://localhost:8000/ws' >> .env &&
      echo 'REACT_APP_AUTH_URL=http://localhost:8000/api/token' >> .env &&
      npm run start:robust"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  frontend_node_modules:
  frontend_reports:

networks:
  sadie-network:
    driver: bridge 