site_name: SADIE Documentation
site_description: Documentation for SADIE - Advanced Trading Data Collection and Analysis System
repo_url: https://github.com/yourusername/SADIE
repo_name: SADIE

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Quick Start: quickstart.md
  - User Guide:
    - Core Components: 
      - Trade Collector: core/trade_collector.md
      - Cache System: core/cache.md
      - Data Models: core/models.md
    - Web Interface:
      - REST API: web/rest_api.md
      - WebSocket API: web/websocket_api.md
      - Dashboard: web/dashboard.md
    - Analysis:
      - Market Cycles: analysis/market_cycles.md
      - Chart Patterns: analysis/chart_patterns.md
  - Development:
    - Contributing: contributing.md
    - Architecture: architecture.md
    - Testing: testing.md
    - Monitoring: monitoring.md
  - About:
    - Roadmap: roadmap.md
    - Changelog: changelog.md 