site_name: sadie
site_description: Advanced Trading Data Collection and Analysis System
site_author: Your Name
repo_url: https://github.com/yourusername/sadie
repo_name: sadie

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            members: true
          rendering:
            show_source: true
            show_if_no_docstring: true

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Modules:
      - Collecteurs: collectors.md
      - Stockage: storage.md
      - Analyse Technique: analysis.md
      - Web: web.md
  - Exemples: examples.md
  - API Reference:
      - Core: api/core.md
      - Data: api/data.md
      - Analysis: api/analysis.md
      - Web: api/web.md
  - Contribution: contributing.md 