[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SADIE"
version = "0.1.0"
authors = [
    { name="Your Name", email="your.email@example.com" },
]
description = "SADIE - Système Avancé d'Intelligence et d'Exécution"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp>=3.9.1",
    "numpy>=1.24.0",
    "pandas>=2.1.0",
    "scipy>=1.11.0",
    "plotly>=5.18.0",
    "pyyaml>=6.0.1",
    "python-dotenv>=1.0.0",
    "websockets>=12.0",
    "redis>=5.0.1",
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "aiofiles>=0.7.0",
    "jinja2>=3.0.0"
]

[project.optional-dependencies]
analysis = [
    "scikit-learn>=1.4.0",
    "dtaidistance>=2.3.10",
    "tslearn>=0.6.3",
    "ta-lib>=0.4.28",
    "arch>=6.2.0",
]
database = [
    "sqlalchemy[asyncio]>=2.0.0",
    "alembic>=1.14.0",
    "asyncpg>=0.29.0",
    "psycopg2-binary>=2.9.9",
]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.11.1",
    "pytest-benchmark>=4.0.0",
    "locust>=2.15.1",
]
dev = [
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
    "pylint>=2.17.5",
    "pre-commit>=3.3.3",
]
debug = [
    "memory-profiler>=0.61.0",
    "py-spy>=0.3.14",
    "psutil>=5.9.0",
    "radon>=6.0.1",
    "xenon>=0.9.0",
    "vulture>=2.7",
    "rich>=13.3.3",
    "ipython>=8.12.0",
    "jupyter>=1.0.0",
]
docs = [
    "mkdocs>=1.4.2",
    "mkdocs-material>=9.1.15",
    "mkdocstrings>=0.22.0",
    "graphviz>=0.20.1",
    "mermaid-cli>=0.5.1",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/SADIE"
"Bug Tracker" = "https://github.com/yourusername/SADIE/issues"

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0330",  # wrong-hanging-indentation
    "C0326",  # bad-whitespace
    "W0511",  # fixme
]

[tool.pylint.format]
max-line-length = 100

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=SADIE --cov-report=term-missing"
testpaths = [
    "tests",
]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "benchmark: marks tests as benchmarks",
]

[tool.coverage.run]
source = ["SADIE"]
omit = [
    "tests/*",
    "setup.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError",
] 