# Configuration générale du projet SADIE

# Paramètres des données
data:
  sources:
    - name: "yahoo_finance"
      enabled: true
      update_frequency: "1h"
      assets: ["BTC-USD", "ETH-USD", "SPY", "QQQ"]
    
    - name: "alpha_vantage"
      enabled: true
      api_key: "${ALPHA_VANTAGE_KEY}"
      update_frequency: "1d"
    
    - name: "twitter"
      enabled: true
      api_key: "${TWITTER_API_KEY}"
      update_frequency: "5m"

# Configuration des modèles
models:
  lstm:
    layers: [64, 32, 16]
    dropout: 0.2
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    validation_split: 0.2
    
  transformer:
    n_heads: 8
    n_layers: 6
    d_model: 512
    dropout: 0.1
    
  hybrid:
    enabled: true
    weights:
      lstm: 0.6
      transformer: 0.4

# Paramètres d'optimisation du portefeuille
portfolio:
  rebalancing:
    frequency: "1d"
    threshold: 0.05
  
  risk_management:
    max_position_size: 0.2
    stop_loss: 0.1
    take_profit: 0.2
    
  constraints:
    min_position: 0.01
    max_position: 0.3
    cash_reserve: 0.1

# Configuration de l'API
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  rate_limit: 100

# Base de données
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "sadie_db"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/sadie.log"
  
# Monitoring
monitoring:
  enabled: true
  metrics:
    - "model_accuracy"
    - "portfolio_performance"
    - "prediction_error"
  alert_threshold:
    accuracy_drop: 0.1
    performance_drop: 0.05 